### ISSUE TITLE
Merge props function mutates given object.

### ISSUE THREAD

**Issue by Aaron-Pool** [vuejs/babel-helper-vue-jsx-merge-props#10]
I suppose this could be _intended_ behavior, but if it is, I think it shouldn't be.

I was writing some stories for my vue storybook and ran into an instance where I was iterating over different variations of a component like so:

```js
render() {
    types = [...blah];
    types.map(t => {
        const data = { attrs: { types[t]: true } };
        <ProfilePic {...data} />
        <ProfilePic url={picUrl} {...data} />
    }
}
```

I was getting odd behavior on the second component, and I managed to track it down to the fact that the `data` object is actually mutated in the creation of the first element. All the props are removed from the `data` object when props are "extracted" and applied to the element.

Is this intended behavior? or a bug? It seems like the data object to be merged should be cloned instead of mutated, but let me know if there's a reason for this. I can create a repro code pen if needed.

**Comment by yyx990803** [comment]
I don't think the issue is from this package. The implementation does not perform any mutations here.
