### ISSUE TITLE
Differences in importing and exporting with babel-plugin-transform-vue-jsx

### ISSUE THREAD

**Issue by niksy** [vuejs/babel-helper-vue-jsx-merge-props#5]
When this helper is injected via `babel-plugin-transform-vue-jsx`, it’s injected as ES `import` signature, but this package uses CommonJS exports signature (`module.exports`) which can create issues with tools like Rollup which expect proper definition as opposed to e.g. Webpack 2 which understands both syntaxes out of the box.

Maybe this should be changed to ES modules `export` by default? Or use `main` for current file, and `module` package.json property for ES version?

**Comment by nickmessing** [comment]
@niksy, I'll try to refactor this project and hope that Evan will have some time to review it so it is available as both ES6 and CJS.
